added workflow

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,21 +1,20 @@
 name: 01 - Building Blocks 
 
-on: [push, workflow_dispatch]
+on: 
+  push: 
 
 jobs: 
   echo-hello: 
-    runs-on: ubuntu-latest 
+    runs-on: ubuntu-latest
     steps: 
-      - name: Say Hello 
+      - name: Say hello 
         run: echo "Hello, World!"
-      
   echo-goodbye: 
-    runs-on: ubuntu-latest 
+    runs-on: ubuntu-latest
     steps: 
-      - name: Failed step 
+      - name: Failed step
         run: | 
-          echo "I will fail"
-          exit 1
-      - name: Say GoodBye 
-        run: echo "GoodBye!"
-        
+          echo "Failed step"
+          exit 1 
+      - name: Say goodbye
+        run: echo "Goodbye!"
